params:
  - training_params.yaml
metrics:
  - reports/metrics.json
stages:
  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
    outs:
      - "data/DL Dataset"
  preprocessing:
    cmd: python src/features/build_features.py
    deps:
      - src/features/build_features.py
      - src/common/utils.py
      - "data/DL Dataset"
    outs:
      - data/tokenized
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/common/utils.py
      - src/models/model.py
      - data/tokenized
    outs:
      - model/model.keras
  test:
    cmd: python src/test.py
    deps:
      - src/test.py
      - src/common/utils.py
      - data/tokenized
      - model/model.keras
  pytest:
    cmd: pytest tests/
    deps:
      - data
      - model
      - output
      - src
      - tests