name: Versioning

on: push

jobs:
  versioning:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Increment version
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Current tag: $TAG"

          NEW_TAG="${TAG%.*}.$((${TAG##*.}+1))"
          echo "New tag: $NEW_TAG"

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: $NEW_TAG
          tag_template: "yyyy.mm.dd.i"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ steps.generate_release_tag.outputs.next_release_tag }}
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: true

      - name: Job Completed
        run: echo "Job finished successfully!"
