name: Versioning

on: push

jobs:
  versioning:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Increment version
        run: |
          TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Current tag: $TAG"

          NEW_TAG="${TAG%.*}.$((${TAG##*.}+1))"
          echo "New tag: $NEW_TAG"

          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Generate release tag
        id: generate_release_tag
        uses: alexvingg/next-release-tag@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: $NEW_TAG

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.generate_release_tag.outputs.release_tag }}
          release_name: Release ${{ steps.generate_release_tag.outputs.release_tag }}

      - name: Create Git Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push --tags

      - name: Job Completed
        run: echo "Job finished successfully!"
